spring:
  datasource:
    url: jdbc:postgresql://ep-tiny-mountain-a8v7bfrs-pooler.eastus2.azure.neon.tech/expensedb?sslmode=require
    username: neondb_owner
    password: npg_gMh3zHAmDW7x
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: h2